### ISSUE TITLE
[BUG REPORT] Issue when using Staff Chat & Discord Integration

### ISSUE THREAD

**Issue by JosTheDude** [frafol/CleanStaffChat#1]
```
[00:03:08 ERROR]: An error occurred while running this command.
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to invoke command sc e for com.velocitypowered.proxy.console.VelocityConsole@651b6f96
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: Unable to invoke command sc e for com.velocitypowered.proxy.console.VelocityConsole@651b6f96
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:223) ~[velocity.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeAsync$0(VelocityCommandManager.java:237) ~[velocity.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
        ... 4 more
Caused by: java.lang.NoSuchMethodError: 'net.dv8tion.jda.api.entities.channel.concrete.TextChannel net.dv8tion.jda.api.JDA.getTextChannelById(java.lang.String)'
        at it.frafol.cleanstaffchat.velocity.staffchat.commands.StaffChatCommand.execute(StaffChatCommand.java:315) ~[?:?]
        at it.frafol.cleanstaffchat.velocity.staffchat.commands.StaffChatCommand.execute(StaffChatCommand.java:28) ~[?:?]
        at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$1(InvocableCommandRegistrar.java:81) ~[velocity.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[velocity.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:210) ~[velocity.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeAsync$0(VelocityCommandManager.java:237) ~[velocity.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
        ... 4 more
```
I just configured my `discord.yml` for CleanSC and keep recieving this error whenever using the plugin in any way (messages, joining and leaving, etc.)

**My config is as follows**
```
discord: # The Discord Integration is an experimental feature, report all problems on our Discord.

  # Toggle discord feature.
  enabled: false

  # Your Discord bot's token.
  token: "(REDACTED)"

  # Types: WATCHING, PLAYING, STREAMING.
  activity_type: "PLAYING"

  # The Discord bot's activity.
  activity: "Minecraft"

  # To use staffchat with Discord, enter the ID of the chat where you want messages to be sent.
  staffchat_channel_id: "1053708662885068846"

  # To use adminchat with Discord, enter the ID of the chat where you want messages to be sent.
  adminchat_channel_id: "1058880068551704586"

  # To use donorchat with Discord, enter the ID of the chat where you want messages to be sent.
  donorchat_channel_id: "1053708662885068846"

  # NOTE: If you do not want to use a certain chat, disable it from modules.
  # You will not have to enter any channel ids if you deactivate them.

  # Use embeds instead of messages.
  use_embeds: true

  # The 'title' of the embed message sent on Discord.
  staffchat_embed_title: "Staff Chat"
  adminchat_embed_title: "Admin Chat"
  donorchat_embed_title: "Donor Chat"
```

**Comment by frafol** [comment]
Hi! Are you sure you have updated to the latest version? Released a while ago.

**Comment by JosTheDude** [comment]
Just updated it and set it up, from Spigot and got that error (around 24 hours ago)

**Comment by frafol** [comment]
What version of the plugin do you have?

**Comment by JosTheDude** [comment]
cleanstaffchat-1.7.4.jar

**Comment by frafol** [comment]
try to remove the "lib" folder in the cleanstaffchat folder and restart the server

**Comment by JosTheDude** [comment]
Issues fixed :D Thanks!
