### ISSUE TITLE
[SUGGESTION] Permission for Joining/Leaving

### ISSUE THREAD

**Issue by JosTheDude** [frafol/CleanStaffChat#3]
It may be good to have a permission // setting to enable silent joining and silent leaving for staff members such as owners, so they can sneak online without notifying other staff members.

**Comment by JosTheDude** [comment]
Thanks for the addition, however, I think there's an issue with the actual NullPointerCheck for the permission itself

```[19:19:12 ERROR]: Couldn't pass DisconnectEvent to cleanstaffchat
java.lang.NullPointerException: permission
        at me.lucko.luckperms.common.cacheddata.type.PermissionCache.checkPermission(PermissionCache.java:101) ~[?:?]
        at me.lucko.luckperms.velocity.service.PlayerPermissionProvider.getPermissionValue(PlayerPermissionProvider.java:60) ~[?:?]
        at com.velocitypowered.proxy.connection.client.ConnectedPlayer.getPermissionValue(ConnectedPlayer.java:907) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
        at com.velocitypowered.api.permission.PermissionSubject.hasPermission(PermissionSubject.java:24) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
        at it.frafol.cleanstaffchat.velocity.staffchat.listeners.JoinListener.handle(JoinListener.java:205) ~[?:?]
        at it.frafol.cleanstaffchat.velocity.staffchat.listeners.Lmbda$21.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:19:18 INFO]: [connected player] SkipTurn (/69.118.50.65:55099) has connected
[19:19:18 INFO]: [server connection] SkipTurn -> earth-1 has connected
[19:19:18 ERROR]: Couldn't pass ServerPostConnectEvent to cleanstaffchat
java.lang.NullPointerException: permission
        at me.lucko.luckperms.common.cacheddata.type.PermissionCache.checkPermission(PermissionCache.java:101) ~[?:?]
        at me.lucko.luckperms.velocity.service.PlayerPermissionProvider.getPermissionValue(PlayerPermissionProvider.java:60) ~[?:?]
        at com.velocitypowered.proxy.connection.client.ConnectedPlayer.getPermissionValue(ConnectedPlayer.java:907) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
        at com.velocitypowered.api.permission.PermissionSubject.hasPermission(PermissionSubject.java:24) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
        at it.frafol.cleanstaffchat.velocity.staffchat.listeners.JoinListener.handle(JoinListener.java:66) ~[?:?]
        at it.frafol.cleanstaffchat.velocity.staffchat.listeners.Lmbda$22.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
This error is thrown when someone with * permissions joins the server

**Comment by frafol** [comment]
you have to reset config.yml after update

**Comment by JosTheDude** [comment]
Did the reset but same issue :')

**Comment by frafol** [comment]
Fixed in latest version.
